# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2E2ODYyNGFiNDE0YjExMmZmNDRiY2Q5YTlkMDE2NThiYTVkMDc4NDhjM2YwZjk3NGU1YTJkYjE3YTc1ZmU3ZDFhN2RkNjEwNzZmMmQyZjdlNDk3ODdjNzY2Y2RhMDE0YmU1NTFjYmY2ZjUxMGM1OTRjOThjYTMxNGI3Y2QzODM=
